/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import GlassesModel from "../../assets/3d/glasses_1.glb";
import { motion } from "framer-motion-3d";

export default function Glasses1({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(GlassesModel);
  return (
    <motion.mesh
      position={[1.1, 0, 0]}
      rotation-z={0.5}
      variants={{
        hover: {
          x: 1.8,
          z: 0.6,
          y: 0.6,
          rotateZ: -0.5,
        },
      }}
    >
      <group ref={group} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glasses.geometry}
          material={materials.Frame}
          scale={0.5}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lens.geometry}
            material={materials.Lens}
            position={[0, -0.01, 0.95]}
          />
        </mesh>
      </group>
    </motion.mesh>
  );
}

useGLTF.preload(GlassesModel);
